---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myniginx
  labels:
    type: sid
    author: sid
spec:
  replicas: 3
  selector:
    matchLabels:
      type: sid
  template:
    metadata:
      name: sid
      labels:
        type: sid
    spec:
      containers:
        - name: mynginx
          image: nginx
...

