---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    type: db
spec:  
  containers:
    - name: mdb
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: name of the secert file
              key: variable of the secret file
...