---
apiVersion: v1
kind: ReplicationController
metadata:
  name: httpd
  labels:
    type: webserver
    author: sid
spec:
  replicas: 3
  template:
    metadata:
      name: http-pod
      labels:
        type: webserver
        author: sid
    spec:
      containers:
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 8080

...
