---
apiVersion: v1
kind: Service
metadata:
  name: tomcat
  namespace: test-ns
  labels:
    type: appserver
    author: sid
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 8080
  selector:
    type: appserver
    author: sid

...