---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    author: Sid
spec:
  type: LoadBalancer
  ports:
    - targetPort: 8080
      port: 8080
  selector:
    type: ci-cd
    author: Sid
...