---
apiVersion: v1
kind: Service
metadata:
  name: httpd_service
  labels:
    type: webserver
    author: sid
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30007
  selector:
    type: webserver
    author: sid
...