---
apiVersion: v1
kind: Pod
metadata:
  name: httpd
  labels:
    type: webserver
spec:
  containers:
    - name: myhttpd
      image: httpd
  tolerations:
    - key: slave2
      value: sid2
      effect: NoSchedule
      operator: Equal
...